stages:
  - stage: BaseEngineLibrary
    dependsOn: [] # Clears dependencies and allows parallel execution
    pool: 
      vmImage: ubuntu-latest
    jobs:
      - job: Cargo_Check_Debug
        dependsOn: []
        steps:
          - bash: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - bash: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions

          - bash: cargo check --verbose --package base_engine
            displayName: Cargo Check (Debug)

      - job: Cargo_Check_Release
        dependsOn: []
        steps:
          - bash: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - bash: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions

          - bash: cargo check --verbose --package base_engine --release
            displayName: Cargo Check (Release)

      - job: Cargo_Build_Debug
        dependsOn: []
        steps:
          - bash: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - bash: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions

          - bash: cargo build --verbose --package base_engine
            displayName: Cargo Build (Debug)
          
          - publish: target/
            artifact: Upload Linux Artifacts (Debug)

      - job: Cargo_Build_Release
        dependsOn: []
        steps:
          - bash: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - bash: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions

          - bash: cargo build --verbose --package base_engine --release
            displayName: Cargo Build (Release)

          - publish: target/
            artifact: Upload Linux Artifacts (Release)

      - job: Cargo_Test_Debug
        dependsOn: []
        steps:
          - bash: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - bash: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions

          - bash: cargo test --verbose --no-default-features --no-fail-fast --package base_engine
            displayName: Cargo Test (Debug)

      - job: Cargo_Test_Release
        dependsOn: []
        steps:
          - bash: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile complete -y
            displayName: Install Rust
          
          - bash: rustc --version && cargo --version
            displayName: Print Rust & Cargo versions

          - bash: cargo test --verbose --no-default-features --no-fail-fast --package base_engine --release
            displayName: Cargo Test (Release)
