name: Base Engine Library

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  base_engine_library:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache target/
        id: target-cache
        uses: actions/cache@v3
        with:
          path: target
          key: library-target

      - name: Install GCC and dependencies
        run: sudo apt-get install -y build-essential gcc gcc-multilib

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

      - name: Install target x86_64-unknown-linux-gnu
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Check
        run: cargo check --verbose --package base_engine_library
      - name: Build (Debug)
        run: cargo build --verbose --package base_engine_library
      - name: Build (Release)
        run: cargo build --verbose --package base_engine_library --release
      - name: Run Tests (Debug)
        run: cargo test --verbose --package base_engine_library --no-default-features --no-fail-fast
        continue-on-error: true
      - name: Run Tests (Release)
        run: cargo test --verbose --package base_engine_library --no-default-features --no-fail-fast --release
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: "base_engine_library_debug"
          path: |
            target/debug/libbase_engine_library.a
            target/debug/libbase_engine_library.d
            target/debug/libbase_engine_library.rlib
            target/debug/libbase_engine_library.so
            target/release/libbase_engine_library.a
            target/release/libbase_engine_library.d
            target/release/libbase_engine_library.rlib
            target/release/libbase_engine.so
          if-no-files-found: error
